#! /bin/bash

# Only rebuild the docker image if running from the git directory.
# Presumably, people wil run this script once from there then copy
# it to somewhere in their PATH
[ -f docker/run-conveyor-and-makerware ] && sudo docker build --tag makerware:latest docker

# Docker app needs access to both the X11 socket, and a file path
# where both the server and client can read/write.  This means the
# file must be visible at the same path both inside and outside of
# the container.
XSOCK=/tmp/.X11-unix
XAUTH="$HOME"/.docker.xauth

# Also need to loosen access since docker container ends up with a
# different hostname.  Or something.  I grabbed this line from StackOverflow
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f "$XAUTH" nmerge -

# Run the container with the X11 settings above, and also share the user's
# home directory, and also inform the container about what UID/GID and
# supplemental groups the user belongs to so it can set up matching /etc
# and have file permissions "just work".
# Also, --privileged seems to be necessary for the conveyor service to
# run, even if you didn't care whether it could access real /dev devices,
# and the conveyor service is required in order to do anything useful with
# makerware, even just generating the x3g files.
if id | grep docker > /dev/null; then
  cmd=docker
else
  cmd="sudo docker"
fi
$cmd run -ti --privileged --rm \
  -e DISPLAY="$DISPLAY" -v $XSOCK:$XSOCK -e XAUTHORITY=$XAUTH \
  -e HOME="$HOME" -v "$HOME:$HOME" -e ID="`id`" \
  makerware:latest
